"""empty message

Revision ID: 256a79be1bd8
Revises: ae0a32b43c39
Create Date: 2018-06-23 17:01:01.057014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256a79be1bd8'
down_revision = 'ae0a32b43c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'status')
    # ### end Alembic commands ###
