"""empty message

Revision ID: ae0a32b43c39
Revises: 
Create Date: 2018-05-05 16:57:17.518417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0a32b43c39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nodeId', sa.String(), nullable=True),
    sa.Column('isemsRevision', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('openMPPTFirmwareVersion', sa.String(), nullable=True),
    sa.Column('timeToShutdown', sa.Float(), nullable=True),
    sa.Column('isPowerSaveMode', sa.Boolean(), nullable=True),
    sa.Column('openCircuitVoltage', sa.Float(), nullable=True),
    sa.Column('mppVoltage', sa.Float(), nullable=True),
    sa.Column('batteryVoltage', sa.Float(), nullable=True),
    sa.Column('batteryChargeEstimate', sa.Float(), nullable=True),
    sa.Column('batteryHealthEstimate', sa.Float(), nullable=True),
    sa.Column('batteryTemperature', sa.Float(), nullable=True),
    sa.Column('lowVoltageDisconnectVoltage', sa.Float(), nullable=True),
    sa.Column('temperatureCorrectedVoltage', sa.Float(), nullable=True),
    sa.Column('rateBatteryCapacity', sa.Float(), nullable=True),
    sa.Column('ratedSolarModuleCapacity', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nodeId', 'timestamp', name='node_timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    # ### end Alembic commands ###
